language: java
install: true

os: linux
dist: trusty
jdk: oraclejdk8

after_success:
  - ./gradlew jacocoTestReport
  - 'bash <(curl -s https://codecov.io/bash)'
  - 'bash <(curl -s https://copilot.blackducksoftware.com/ci/travis/scripts/upload)'