language: java
branches:
  only:
    - master

install:
  - mvn install -DskipTests=true -Dgpg.skip=true -Dmaven.javadoc.skip=true -B -V

after_success:
  - ./gradlew jacocoTestReport
  - 'bash <(curl -s https://codecov.io/bash)'